### ISSUE TITLE
Multiselect with mode 'Checkbox' mousedown event-listener

### ISSUE THREAD

**Issue by otrebor-bni** [syncfusion/ej2-angular-ui-components#49]
Hi team,

I'm using the multiselect-dropdown control with mode 'checkbox' and it seems that there is something wrong with adding and removing the 'mousedown' event listener of the control.

Module CheckBoxSelection
File: "node_modules\\@syncfusion\ej2-dropdowns\src\multi-select\checkbox-selection.js"

During initialization of the control, the mousedown event listener gets registered on 'document' level but after the component where the control is used gets destroyed, the listener won't be removed. 
this.parent.isDestroyed is always true:

`
CheckBoxSelection.prototype.removeEventListener = function () {
        if (this.parent.isDestroyed) {
            return;
        }
`

following code will never get executed:
`
 EventHandler.remove(document, 'mousedown', this.onDocumentClick);
`

And because the listener is registered on document level, other listeners like 'click'-events' won't work because of that.

Used Packages: 
    "@syncfusion/ej2-angular-base": "^17.2.39",
    "@syncfusion/ej2-angular-calendars": "^17.2.36",
    "@syncfusion/ej2-angular-dropdowns": "^17.2.40",
    "@syncfusion/ej2-angular-lists": "^17.2.34",
    "@syncfusion/ej2-angular-navigations": "^17.2.40",
    "@syncfusion/ej2-angular-pdfviewer": "^17.2.40",
    "@syncfusion/ej2-angular-popups": "^17.2.35",
    "@syncfusion/ej2-base": "^17.2.40",
    "@syncfusion/ej2-buttons": "^17.2.35",
    "@syncfusion/ej2-dropdowns": "^17.2.40",
    "@syncfusion/ej2-inputs": "^17.2.34",
    "@syncfusion/ej2-pdfviewer": "^17.2.34",
    "@syncfusion/ej2-popups": "^17.2.35",

- NodeJS: 12.6.0
- AngularCLI: 8.1.2

**Comment by BerlyChristopher** [comment]
Hi Otrebor,

Greetings from Syncfusion support. 

We were unbale to reproduce the reported issue in the product version **17.2.0.41** and we would like to inform you that we were unbound all the events while component gets destroyed. So, we suggest you to upgrade your dropdown packages to the latest version (17.2.0.41) and ensure that the reported issue is resolved or not. We have prepared the sample and attached it below. 

**Sample Link**: https://stackblitz.com/edit/angular-jmbgze-cniwvg?file=app.component.ts 

Still, the issue persists in **17.2.41** version, please revert us with **issue reproducing sample** or **code example** or **modify the providing sample with the reported issue** that will help us to check and provide the exact solution at our end. 

Regards,
Berly B.C

**Comment by otrebor-bni** [comment]
I still get this error with latest version of multi-select control (checkbox mode).
I'm also using the latest version of Kendo UI (for Angular)  -> Kendo Dropdown Buttons
"@progress/kendo-angular-buttons": "^4.2.0"

If I open a page which contains a Multi-Select Control (Checkbox Mode) and then trying to click on the Dropdown Button List, no event will be triggered. I guess, the problem is something about the "mousedown" listener which both controls are using..

Error occurs:  TypeError: Cannot read property 'setAttribute' of null
![image](https://user-images.githubusercontent.com/54057524/76538879-4a198780-6480-11ea-8da7-8f661a368758.png)

**Comment by BerlyChristopher** [comment]
Hi Otrebor,

Thanks for the update.

We have tried to reproduce the reported issue by rendering the Kendo UI Angular DropDownButton and Syncfusion EJ2 MultiSelect component in the same page. But the reported issue is not reproduced at our end. Please find the sample from the below link.

**Sample Link**: https://stackblitz.com/edit/angular-jmbgze-1bag6e?file=app.component.html 

Please check the above sample and let us know where we have missed to reproduce the reported issue at our end. Also, please share the below details to help us an d proceed further. 

- Have you rendered our EJ2 MultiSelect component inside the Kendo Angular components or rendered both controls on the same page?
- Share code example or sample sufficient to replicate the issue.
- Any screenshot of the issue or video demonstration to replicate the issue 

Regards,
Berly B.C

**Comment by ajithr** [comment]
We are closing this thread since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.
